### ISSUE TITLE
Docs - HIG - Formatting issue on German translation

### ISSUE THREAD

**Issue by tvw** [elementary/mvp#1113]
### Expected behavior

No scrollbar in the document at all.

### Actual behavior

The document has a scrollbar though the browser provides a scrollbar by itself.
(Funny behaviour on a webpage about UI design ;-) )

And: it is not working at all, since it can be scrolled up and down itself by the browser scrollbar and it behaves as if the content is smaller than the screen and does not allow scrolling.

Scrolling through the page up and down keys is prevented, though the whole documentation is in one page.

### Steps to reproduce the behavior

1. Goto [https://elementary.io/de/docs/human-interface-guidelines#human-interface-guidelines](https://elementary.io/de/docs/human-interface-guidelines#human-interface-guidelines)

### System information

- **Operating system**: Ubuntu Linux
- **Operating system version**:  14.04
- **Browser**:  Firefox
- **Browser version**: 45.0.1 
- **Browser**:  Chrome
- **Browser version**: 50.0.
- **Browser**:  Vivaldi
- **Browser version**: 1.0

**Comment by cassidyjames** [comment]
Interesting, not an issue on the English version. It looks like there is also a syntax error somewhere in the German translation causing teh rest of the page to be formatted improperly (like a missing `</code>` or `</pre>` tag). I believe the scrollbar is being added because the browser things the rest of the page is a part of that code block.

**Comment by lewisgoddard** [comment]
Here's your problem, that is not how you close a code block. https://github.com/elementary/mvp/blob/master/lang/de/docs/human-interface-guidelines.json#L457
