### ISSUE TITLE
Entering $0 switches back to $10 in Firefox

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#1192]
Reported via Twitter

 https://twitter.com/dkomm/status/746053028822810624?s=09

**Comment by lewisgoddard** [comment]
Unable to confirm using Firefox 47 for Linux.

**Comment by fabianthoma** [comment]
I can confirm, but only when I enter a $ Sign as well, then the input does not validate and switch back to the default $10 button.

**Comment by lewisgoddard** [comment]
So the problem here is that `input type="number"` doesn't restrict you to entering only digits in the field in some browsers. Perhaps the handler could strip out anything except `0-9.` and if that's a valid number replace the value.

**Comment by shockry** [comment]
It seems like there's no way to get the value of an invalid input..

Another approach would be to listen to key presses and filter out all printable characters other than `0-9.` , and the backspace, though that would require keeping track of the count of decimal points ("." character) and number of digits after it (if more than two, it's invalid because of the current "max" attribute).

On a side note, I also found out that chrome allows the "e" character (treats it as exponent)

**Comment by lewisgoddard** [comment]
I agree, we should probably filter out invalid characters by blocking their input on the field.

**Comment by aadrian** [comment]
The problem is that other specialized input field types except ```text``` behave differently across browsers but even worse when users have different locale. 

The usual solution is to use only ```text``` and do the job with JavaScript. 
E.g. this jQuery plug-in does the job: https://igorescobar.github.io/jQuery-Mask-Plugin/ but there are many plug-in alternatives, so that no or minimal  JS coding is required.

**Comment by lewisgoddard** [comment]
Yeah, value really isn't consistent enough across browsers to be much help.

**Comment by lewisgoddard** [comment]
This no longer appears to occur.
