### ISSUE TITLE
Animate the hero image

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#129]
Our hero "image" should be a video/gif that shows off some basic parts of our desktop. What is it like to find & open apps? How about multi-tasking. Notifications.

A sexy 30sec overview/intro (with no sound).

**Comment by devTristan** [comment]
If somebody else makes the video I can make this happen.

**Comment by Tajnymag** [comment]
I'll do it in next 24 hours.

**Comment by Tajnymag** [comment]
I made a quick screencast loop. It's not the best one and I still see a lots of problems there but, Hey! :smile: What do you think?

[The video on my GDrive](https://drive.google.com/file/d/0B-K8l_xTlaFrZDZyMDdJb1huQTA/view?usp=sharing)

**Comment by devTristan** [comment]
This is really cool! A couple ideas:

* Maybe use another background? I love the beta background but it isn't what people will recognize when Freya hits.
* How about showcasing "lifestyle" apps like Music and Photos? Maybe with some smooth indie jams so that people won't think elementary is for squares, and some family photos so that people will think elementary is for well adjusted people.
* Do you have any way of recording this at a higher frame rate? The smoothness of elementary is relatively unique and should be showcased on the front page, IMO.
* 1080p would also be good, for those mad high res screens the kids have these days.

**Comment by Tajnymag** [comment]
Unfortunately, I can't do the video any smoother. I am running the Elementary OS in VirtualBox and this is the best fps I can get iwith everything maxed out.
Here is the second version: 
[video_n°2](https://drive.google.com/file/d/0B-K8l_xTlaFrMHREWXpFcGF6eUE/view?usp=sharing)
[my poster](https://drive.google.com/file/d/0B-K8l_xTlaFrN3NjdDVseko4X0U/view?usp=sharing)

**Comment by aleksandar-todorovic** [comment]
I don't think that you need to showcase because that package is not a part of elementary OS and it is not available on the clean system.

**Comment by Tajnymag** [comment]
What shouldn't I showcase?

**Comment by Tajnymag** [comment]
RE: devTristan
How about this? Inside cut laptop screen div, of course :smile: 
```
<video class="hero" src="video.webm" poster="poster.png" autoplay></video>
```

**Comment by devTristan** [comment]
@aleksandar-todorovic Sorry, I thought noise and pantheon photos both came w/ freya?

@Tajnymag This is a really nice video!
Your markup is exactly right. For the poster, the first frame of the video (or an identical screenshot with no compression) would be ideal. Maybe the video could be shot without a VM? If you're already running the Freya Beta, you could create a fresh user account and use that.
Not personally a huge fan of the concert pics, mainly having them full-screen, because a user who glances at the video half way through would be like "wtf"

**Comment by Tajnymag** [comment]
@devTristan Unfortunately I am running Windows 8 so this is for me the only "clean"  way to do it. I don't want to set a dual boot for now. I agree the photos are weird, but they were the only stylish/indie/royalty-free photos I've found.

**Comment by devTristan** [comment]
@Tajnymag No problem! I'll take a look at adding this tonight.

**Comment by aleksandar-todorovic** [comment]
@devTristan You misunderstood me. I'm not talking about Noise _nor_ Pantheon Photos. I'm talking about a cowsay command ran in the terminal in both of the videos @Tajnymag posted here. That cowsay package does not come with the default installation of elementary OS. It is available through the `apt-get install` command, but it is not a part of the default installation. The same thing applies to that train animation in the terminal in the first video.

Also, @Tajnymag, please keep in mind that elementary OS always spells with a lowercase letter 'e', not with an uppercase.

I'd love to record that video in higher fps and I do have Freya running, but unfortunately my laptop monitor is 15.6", which means it is not big enough to record a 1080p video.

**Comment by devTristan** [comment]
Ah, that's a good point about the cowsay command. I have a 4k display but my elementary install is a bit broken and I don't have time to fix it.

P.S. Many 15 inch screens have 1080p+ resolution.

**Comment by danrabbit** [comment]
Yes please avoid showing Terminal altogether. In fact I wouldn't do anything that requires typing. Keep in mind this image would be embedded on the page so it'll probably be pretty small. You'll only really see things that are pretty big. Focus on differentiating features (like multitasking).

**Comment by RoryJ-** [comment]
The notebook image should probably be an svg or at least have good anti-aliasing.

The resolution should be 1080p (16:9). Obviously it shouldn't be in a VM as the frame-rate is horrible. Until the gala maximize bug has been fixed, the video shouldn't have any maximizing as that animation looks pretty bad.

The video should only show what the average user would do - no terminal or power user stuff. Just music, photos, web browsing, multitasking and using slingshot should do.

**Comment by devTristan** [comment]
@RoryJ- You're so right! You seem to have a good idea of what should happen in the video, would you be able to record it?

I couldn't find an SVG of the notebook in the images folder. Does anybody have one lying around or was it drawn in raster?

**Comment by devTristan** [comment]
I just shot this:

http://a.pomf.se/pzkqcl.mp4

60fps, 1080p, mp4. The content of the video is simple. I open midori, which brings up the elementary blog. I switch to my second desktop and look at an empty calendar. I switch back and close midori, back to where I started (intended for loop.)

I have a few problems with it:

 - it's kinda boring
 - 1080p isn't my native resolution, and it shows a bit
 - midori doesn't seem to handle hidpi very well, so that's a bit blurry
 - the SimpleScreenRecorder icon is visible

Since the video will be pretty small, it's possible that those things won't matter.

If anybody has any ideas, or different things I could try recording, let me know. One of these days I'll try to resize the laptop image, bring in a good video, and get my PR to a serviceable place.

**Comment by aleksandar-todorovic** [comment]
@devTristan Website not available?

**Comment by devTristan** [comment]
Does the link not work? That's odd, it works just fine for me.

Try this: https://mega.co.nz/#!khtlUIyJ!g9GDguNegvX4V0suBOloVP6h44EzTfhdxs74uhBqf1k

**Comment by danrabbit** [comment]
I'm gonna close this since we haven't decided on a design direction for a full year
