### ISSUE TITLE
Link the get involved desktop dev to the getting started guide

### ISSUE THREAD

**Issue by PerfectCarl** [elementary/mvp#249]
http://elementaryos.org/docs/code

**Comment by danrabbit** [comment]
Hm that guide is more focused on 3rd party developers though. There's reference material about reporting bugs, but it's not really a guide for hacking on other people's stuff as much as a guide on building your own stuff.

**Comment by PerfectCarl** [comment]
This guide is crucial for any developer to get started with the elementary stack (launchpad, cmake, granite, etc.)

Even someone that intends to fix an issue on an existing app needs to register to launchpad, get the source and dependencies (apt-get buil-dep etc).

Besides no one can know what will be the nature of the contribution.
It can be new plugins. 
The recent example of the calculator is a good indicator of that.
 
The existing doc does a good job of introducing how to contribute to elementary.
It misses how to debug the application and more crucially how to get support from the elementary team.

Between launchpad, reddit, g+ and that ever elusive slack, a new contributor should know how to ask questions and contact the team.
(And I won't even mention IRC as it is a waste a time)

The last thing is to link to a well written descriptive list of suggestions for a newcomer.
Like the one that you provided embik when he wanted to get onboard.
That list should be advertised and kept up to date every two months.

Blueprints and wishlist bugs are not helpful enough.

**Comment by PerfectCarl** [comment]
Also see #283 for a discussion about getting started for developers

**Comment by danrabbit** [comment]
Okay a single bug report isn't the place to enumerate every request you have. Please file separate reports for each individual issue. All this documentation isn't going to be written all at once and probably not by the same person.

I'd argue that the "Get Involved" page assumes you already know how to code for elementary OS. It's not designed to be a tutorial. That job is done by the "Developer" page (which hasn't landed here yet).

I'm going to close this report due to the above. Again feel free to open separate reports for each new section of documentation you'd like to see.
