### ISSUE TITLE
HTTPS should be enforced when available [$50]

### ISSUE THREAD

**Issue by aleksandar-todorovic** [elementary/mvp#258]
Although we do have HTTPS support enabled, for some reason, it's not currently on by default. I think that it is time we enable the visitors to browse the site securely by default.

**Comment by cassidyjames** [comment]
@fabianthoma do we have certs and everything for this? I'm all for switching to HTTPS by default if we can.

**Comment by gamerlv** [comment]
We currently don't own any SSL certs ourselfs. The current site SSL is provided by [Cloudflare's Universal SSL](https://www.cloudflare.com/ssl).

**Comment by 19kestier** [comment]
Using Cloudflare for SSL is an awful idea. It's very susceptible to Man in the Middle attacks.
http://www.jupiterbroadcasting.com/74772/cloudy-with-a-chance-of-ssl-techsnap-195/
http://blog.ricardomacas.com/index.php?controller=post&action=view&id_post=4
I'm not recommending GoDaddy, but they do offer free SSL certificates for open source projects.
https://www.godaddy.com/ssl/ssl-open-source.aspx

**Comment by quassy** [comment]
With a bit of luck (they promise mid 2015) [Let’s Encrypt](https://letsencrypt.org/) is available in time for the website launch.

**Comment by ApfelUser** [comment]
[StartSSL](https://www.startssl.com/?app=1) is also for free.

**Comment by lewisgoddard** [comment]
I think the only thing currently stopping this is our lack of a "real" ssl certificate.

$25 for 5 years => https://www.ssls.com/comodo-ssl-certificates/positivessl.html

**Comment by lewisgoddard** [comment]
Okay, so Midori doesn't support our SSL with Cloudflare, so for now it will be optional. Leaving this open and blocked.

**Comment by quassy** [comment]
Is there a corresponding bug report open with Midori? Cloudflare SSL/TLS is quite common :o

**Comment by lewisgoddard** [comment]
Midori is working on a Gtk3/WebKit2 version that presumably fixes the problem. However because the core of Midori has become so outdated it is a major rebuild and is taking some time, hence it won't be coming by default in Freya, although it might come through as an update.

**Comment by CameronNemo** [comment]
@ApfelUser StartSSL charges for multiple subdomains. It is 60 dollars https://www.startssl.com/?app=2

**Comment by danrabbit** [comment]
Lewis had an idea about using JS trying to see if the browser can load a file over https and then redirecting if true. I think that sounds like a good workaround for the issue which should provide https for browsers that can handle it and not exclude those that can't.

**Comment by lewisgoddard** [comment]
The issues isn't that we can't get an SSL certificate, [3 years for $15](https://www.ssls.com/comodo-ssl-certificates/positivessl.html) is nothing. The issue is we currently hide behind Cloudflare to deal with most of our traffic. As a result, we are stuck using their SSL system. The smallest plan we can get for custom SSL is $200 a month, which is outside our budget right now.

I do however have a solution. As danrabbit said, we use a small javascript snippet to asynchronously load a secure resource onto the page. That resource, on error, does nothing. On success, the browser will receive a [HTTP Strict Transport Security Header](http://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security). When a HSTS Header is received, a compliant browser should redirect insecure requests in the specified time period before sending them to the server.

> When a web application issues HSTS Policy to user agents, conformant user agents behave as follows:
> Automatically turn any insecure links referencing the web application into secure links. (For instance, http://example.com/some/page/ will be modified to https://example.com/some/page/ before accessing the server.)
> If the security of the connection cannot be ensured (e.g. the server's TLS certificate is self-signed), show an error message and do not allow the user to access the web application.
- http://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security

To be clear, **for successful bug closure**, we require:
1. A JavaScript snippet that asynchronously fetches...
2. A PHP page which sends a valid HSTS Header along with a minimal JSON response. The header should have a near-maximum expiry time.

**Comment by ApfelUser** [comment]
I want to remember you guys on my comment before. You can get free SSL certificates which last for one year at [StartSSL](https://www.startssl.com/). You'd get rid of all the problems you have. Midori would accept the SSL certificate and you could enable HSTS with all the (sub-)domains.

**Comment by gamerlv** [comment]
@ApfelUser Thanks for the reminder but it's not that simple unfortunately.

It is **not** about the certificate. We can not switch to https only because midori still uses webkit **1**. This older version of webkit does not support the right *[chipers and encryption methods](https://support.cloudflare.com/hc/en-us/articles/200933580-What-cipher-suites-does-CloudFlare-use-for-SSL-)* Cloudflare uses in their SSL implementation.
The $200 is the cost per month of having any custom (even a free one) certificate in Cloudflares system. Which is money we would rather spend on bounties.

**Comment by lewisgoddard** [comment]
I was under the impression it was Server Name Indication (SNI) that was incompatible with Midori, the selected [protocols and ciphers](https://github.com/cloudflare/sslconfig/blob/master/conf).
