### ISSUE TITLE
Figure out what to do about navbar overflow

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#275]
So navbar currently breaks into two lines at iPhone 5 size. Feels weird.

**Comment by alexgleason** [comment]
This needs design however. A common approach would be to just enlarge the logo, then have clickable menu button at the side that reveals the nav items in a menu.

For instance, here is a mobile nav menu I recently implemented at my work:

![screen shot 2015-04-17 at 4 47 18 pm](https://cloud.githubusercontent.com/assets/3639540/7211567/a501b12e-e521-11e4-8c37-57d5a8cc1054.png)

Clicking the "Menu" button toggles the visibility of the nav items.

I can implement something like this if the solution is agreed upon.

**Comment by harveycabaguio** [comment]
Can we try making the navbar scroll horizontally?

![](http://material-design.storage.googleapis.com/publish/material_v_3/material_ext_publish/0B_udO5B8pzrzbUVlc0RlX0puYTg/components_tabs_usage_mobile5.png)

**Comment by alexgleason** [comment]
I don't think making the nav scroll horizontally would work here. In the Android app, those are tabs which are swiped through. You wouldn't want to implement just the nav without the rest of the functionality or you'd risk making a frankendesign. Especially so when this pattern isn't seen on the rest of the web.

And I don't think it's viable to implement the rest of the site in that way. It would make the site clunky and slow and probably never work right. It works for the app since the app's UI is all offline and part of the user's system.

The expandable menu is the best option. It's what web users expect, it allows any number of thumb-sized nav links, and coincidentally, it's even consistent with elementary apps.

Does anyone disagree here?

**Comment by alexgleason** [comment]
There's no indication to the user to scroll the navbar. It looks like the whole page is overflowing but you can't scroll horizontally except directly over the nav bar. IMO this isn't fixed.

**Comment by danrabbit** [comment]
You could probably open a new report about adding some kind of scroll indication
