### ISSUE TITLE
Need better docs for Desktop Development

### ISSUE THREAD

**Issue by agauniyal** [elementary/mvp#283]
Beta version of site shows these 3 : 

+ Browse Our Desktop Code 
+ Browse Our Apps' Code 
+ See Our Open Bug Reports 

and the previous [docs](http://elementaryos.org/docs/code/getting-started) was a bit better but not good enough ( from my perspective ). I have done a quiet amount of development in WP , WIndows desktop and metro apps . and I agree that they are lot widespread than eOS is , but to be a little bit developer friendly , you guys need to invest some more time in those docs. It would be great if you guys provided some more examples than "Hello World" app.

**Comment by danrabbit** [comment]
OP, I am closing this report because it contains no clear actionable items. "Make foo better" is not something that can ever be achieved. Reports need to be able to be closed at some point.

Keep in mind also that the "Get Involved" page is not designed to be a tutorial. There is another section planned ("Developer") that is designed to provide a tutorial. When it is copied over to this beta site, please feel free to file separate, specific, actionable reports against it.
