### ISSUE TITLE
Store opening in new tab is odd

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#290]
Last night we merged in our new store page and made it open in a new tab so users wouldn't be taken completely away from our site when checking out. However, this introduced a new problem:

The store page itself is still a part of our site, so using the navbar there gives you two tabs with the site in it.

Instead, we should see if we can use some js magic to make Square's checkout button open in a new tab and keep the store in the original tab.

**Comment by emersion** [comment]
The problem here is that the store is embedded using an `<iframe src="https://squareup.com/...">`. The checkout button is in that iframe and we can't bind events to it due to security reasons. :-(

I don't think we'll be able to do that with JS. Maybe there is an option to provide to Squareup in order to have this behaviour?

**Comment by cassidyjames** [comment]
@emersion I looked in the Square dashboard last night and didn't see anything, but I'll keep digging.

**Comment by cassidyjames** [comment]
Yeah, getting Square's iframe to open in a new tab is not gonna happen. So that means either:

1. We link to the store externally altogether, and open it in a new tab, or
2. We keep the store embedded and live with the fact that the user goes offsite when they give us money.

**Comment by danrabbit** [comment]
Yeah I'm also on board with #2. Closing this issue

**Comment by cassidyjames** [comment]
Uuuuh reopening until I implement number 2 :stuck_out_tongue:
