### ISSUE TITLE
Download process is unclear on pricing

### ISSUE THREAD

**Issue by devTristan** [elementary/mvp#342]
Nowhere is it specified that the user can pay what they want, or nothing at all. It will take the average user a significant amount of time to figure out how to download it for free, if they figure it out at all. Currently, unless a user already knows the pricing scheme, they'll almost definitely think that elementary OS costs money.

This could be solved a few ways. Language like "pay what you want" or "Click custom to enter any amount" is ideal IMO, because it makes the user aware of the pricing scheme.

Currently the "Download Freya Beta" button opens a payment modal, which breaks user assumptions.

**Comment by danrabbit** [comment]
I'm going to close this as "Opinion". We don't want people to pay $0. You shouldn't download for free. You should choose a price and pay. If you download for free, congratulations. But the idea is that you should pay some fair amount.

**Comment by devTristan** [comment]
You're trying to guide users towards paying for the product, which is a fine idea. This is a usability issue. The lack of clarity in this interface affects all users, regardless of whether or not they intend to pay.

**Comment by cassidyjames** [comment]
@devTristan it's extremely clear that users can pay $10, $25, $50, or Custom. When they click custom, it tells them they can "enter any dollar amount". This is a non-issue.

**Comment by devTristan** [comment]
Have you guys considered usability testing or a tool like [inspectlet](https://www.inspectlet.com/) to understanding common user behaviors without having to rely on assumptions?

**Comment by cassidyjames** [comment]
@devTristan yes, we have. However we don't currently have the resources to perform thorough usability testing. Inspectlet looks interesting. I'm not sure we want to add yet another HTTP query to pull in a third-party's js, though, especially for something as simple as the download page.

I get that you want to make sure users understand the page, and I respect your approach. I get that we shouldn't assume things. However, we've experimented with different pay-to-download ideas for elementary OS since 2011 and are didn't just decide to do it this way on a whim; we've looked at our download numbers, payment numbers, website analytics, and user feedback to better understand how users behave. That said, it's also not set in stone and we can always adapt in response to further feedback.

If you'd like, feel free to open an issue about adding inspectlet as that's a separate request.
