### ISSUE TITLE
Support for paypal

### ISSUE THREAD

**Issue by danielalmeidagoncalves** [elementary/mvp#375]
I dont know if this is already in the plans, but it was cool if the new beta site could give the oportunity to donate through paypal (as is already possible in the actual main elementary site), for now the only integration available as I can see is with stripe (credit card).

**Comment by cassidyjames** [comment]
I've wondered about this as well. We do get the majority of payments through PayPal rather than direct credit cards. On the other hand, PayPal isn't the best experience nor partner to work with, and I don't like adding another step/option to the payment process. 

Leaving this open as a wishlist for now.

**Comment by drunknzombiecow** [comment]
I would love to see PayPal as well. Since I live in Germany and you actually never need a credit card here unless you go on vacation somewhere else I don't have a credit card. For the moment it's fine because it works on the current website but for future payments I'll be literally cut off from supporting.

**Comment by danielalmeidagoncalves** [comment]
From my point of view cutting down paypal support may compromise a few supporters. But in the other hand I understand that this integration may lead to superfluous development work. If the problem is adding another step/option to the payment process, why not giving a kind of alternative link option somewhat in a way that will not result in the other set/option in the main support method. I dont know if I made myself clear...

**Comment by geocool** [comment]
I usually don't add my credit card to websites except for paypal & some high secure services like amazon. At first on the donation process I was hesitant when I had to enter my credit card. I didn't event know what stripe service is. Paypal provides security for the user and the process of paying is really fast.

**Comment by lewisgoddard** [comment]
There is now paypal support on `/get-involved`

**Comment by danielalmeidagoncalves** [comment]
Glad to ear that! It felt great to donate to this project :)  thanks for all.
