### ISSUE TITLE
Libre office

### ISSUE THREAD

**Issue by yoga30696** [elementary/mvp#376]
Why can't elementary come along with any of the office suite available?

**Comment by lewisgoddard** [comment]
This isn't a place to report bugs or make suggestions for elementary OS i'm afraid, it is purely for the site beta.elementaryos.org That said, I will try to answer your question quickly, because I know how annoying bug trackers can be.

elementary OS made a preliminary decision to not include an office suite for a variety of reasons, the most major being the upkeep and design on the suite. LibreOffice does not neatly fit with the elementary aesthetic, and it's design is not something that can be changed adequately with theming. Some simple procedures need to have their entire flow re-written to properly follow the elementary Human Interface Guidelines. Including software in elementary is an endorsement, and endorsement that states that it has met a certain level of structure, stability and design. I do not believe elementary feels and such suite has currently met these levels.
