### ISSUE TITLE
Get involved should also a small setup tutorial for php developers

### ISSUE THREAD

**Issue by ferst9** [elementary/mvp#400]
Contributing to Launchpad apps is well explained but contributing to the website not really.
Maybe a simple tutorial for using github and how to configure your IDE to submit a branch would be enough.
There is no need for a php introduction.

**Comment by agats** [comment]
Hi @ferst9 ,

There is some documentation with the [README.md](https://github.com/elementary/mvp/blob/master/README.md) to start up your local dev  environment. And there is documentation within [CONTRIBUTE.md](https://github.com/elementary/mvp/blob/master/CONTRIBUTE.md) for the code and review expectations of the project.

**Comment by KeitIG** [comment]
How we're going on this one ? I don't feel the need to do this since as mentionned @agats: we have a README.md and a CONTRIBUTE.md + a link to this repo.

**Comment by fabianthoma** [comment]
Yeah I also agree with the above. The readme and contribute files are pretty common on github, and I think they explain pretty well what to do. If people run into issues these should be updated, there's no reason to also put it on the website, since webdevelopment is not really related to elementary OS.
