### ISSUE TITLE
Link to Transifex from Get Involved

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#402]
We should add a link to the translations section and also modify the copy to indicate where website translations occur

**Comment by aleksandar-todorovic** [comment]
Maybe something like this?

![screenshot from 2015-02-15 21 10 51](https://cloud.githubusercontent.com/assets/4890548/6204776/56561f5a-b557-11e4-92ff-72d36163f522.png)

Or maybe we should lose the "Get more info" buttons all together like this.

![screenshot from 2015-02-15 21 14 12](https://cloud.githubusercontent.com/assets/4890548/6204797/b185088c-b557-11e4-96a2-bf4d2c072ff1.png)

I think that we should also update the paragraph above because we no longer use Rosetta exclusively.

**Comment by danrabbit** [comment]
Yeah the paragraph would need to be updated :) I think we could probably reduce the marketing speak here and make the "call to action" buttons a little more direct. Maybe something like:

elementary OS uses an open, collaborative translation tool on Launchpad called Rosetta. Learn More >
Our website is also openly translated, but instead of Rosetta it uses Transifex. Learn More >

[ Translate elementary OS ]
[ Translate This Website ]

**Comment by aleksandar-todorovic** [comment]
Maybe this is a good solution? Basically keeping the first sentence unchanged, deleting the second sentence and then doing your suggestion.

![screenshot from 2015-02-15 21 46 36](https://cloud.githubusercontent.com/assets/4890548/6204948/8b4e2fe0-b55c-11e4-8ba7-77cb85800265.png)

Btw in my opinion `Translate elementary.io` sounds better than `Translate This Website`.

**Comment by danrabbit** [comment]
Yeah that looks good to me. I was concerned about the buttons not looking different enough with "elementary OS" and "elementary.io". I originally wrote that, but it was weird to me

**Comment by aleksandar-todorovic** [comment]
OK then, it is a bit too late now, but if there are no other suggestions until I wake up I will create a pull request.
