### ISSUE TITLE
add our irc-channel #elementary

### ISSUE THREAD

**Issue by PhillipSz** [elementary/mvp#420]
It would be really great if you can add it to the support page. Because its still an active channel so why not show that? Maybe just link to https://kiwiirc.com/client/chat.freenode.com/elementary Thanks alot!

**Comment by aleksandar-todorovic** [comment]
My biggest problem with our IRC channel is that people don't wait at all to get an answer. If we don't answer them in less than a minute, they will leave the room.

So maybe adding it but saying that it could take like a half an hour to get an answer?

**Comment by PhillipSz** [comment]
Yeah I'm totally fine with that :)

**Comment by davidak** [comment]
@aleksandar-todorovic something like that should be the MOTD in the channel, like others have.

**Comment by PhillipSz** [comment]
@davidak it is in the topic: "Please ask your question directly and wait for an answer!"

**Comment by quassy** [comment]
I'm against adding it, for the reasons @aleksandar-todorovic mentioned. It leads to unneeded frustration with elementary. And for support the main problem with IRC is that it is not searchable, saved etc, so you have to answer the same questions all over again because you can't just link to a previous IRC conversation. Generally Reddit, Google+, Launchpad Answers and hopefully elementary on SE are a much better means to provide support.

**Comment by PhillipSz** [comment]
which is wrong as wie can habe an archive. (as we have for #elementary-dev)

**Comment by quassy** [comment]
Fair enough, but it is still much harder to reuse a solution from a log of unstructured IRC messages where there are other people talking in between. (One would probably link to something along the lines of logs.elementary.io/elementary?messages=414-424)

**Comment by PhillipSz** [comment]
yeah, right. But it is only an option, not a must use.
