### ISSUE TITLE
Display the average payment to encourage competitiveness for larger payments.

### ISSUE THREAD

**Issue by davidak** [elementary/mvp#421]
and some more statistics in realtime like HumbleBundle does?

maybe that motivates someone to pay more than the average or more than the average windows users.

but maybe that value will be very low because only 0,1% will pay. then one will think: "why should i pay if no one else does"

what do you think?

**Comment by lewisgoddard** [comment]
This seems like a good idea, but we'll need a small database set up to store the information. This seems like overkill since it can be done with a couple of fields.

### Example

Lets say 2 users pay $10 each.

total | count | average
-------- | -------- | --------
20 | 2 | 10

Then, someone pays $20. We take the current total, add the new 20 to it, add one to the count, and divide out.

total | count | average
-------- | -------- | --------
40 | 3 | 13.33

This system means no storing of personally identifying information, so no need for complicated compliance issues.

**Comment by lewisgoddard** [comment]
We could even steal the thing from https://github.com/elementary/mvp/issues/350#issuecomment-72741112 and do a breakdown by operating system as well.

os | total | count | average
-------- | -------- | -------- | --------
total | 100 | 10 | 10
osx | 30 | 3 | 10
windows | 40 | 5 | 8
linux | 30 | 2 | 15

**Comment by gamerlv** [comment]
Having more metrics available is always a good thing. Maybe even have the system average as last suggested option, "Beat the average".

My initial though is not store any total fields in a database, Since it's possible to calculate them from the data stored. The only reason for storing totals would be to decrease page loading time.

**Comment by lewisgoddard** [comment]
Since the averages will be rounded to decimal figures, it will introduce gradual discrepancies if we multiply out the averages every time. Considering the tiny amount of data being stored, one extra column shouldn't hurt.

**Comment by lewisgoddard** [comment]
Would we be interested in the mean average, or the moda average?
Modal requires logging each payment.

**Comment by lewisgoddard** [comment]
Assuming we still want this, I have a branch which needs some design but can both log and return mean averages of payments.
