### ISSUE TITLE
Add a separate Features page

### ISSUE THREAD

**Issue by cassidyjames** [elementary/mvp#493]
A lot of people have been asking on Twitter, Hacker News, and elsewhere about the features of elementary OS. We could provide a page, linked from the home page, that outlines the included apps and features.

Here's a doc I started with the sort of info that could be on the page: https://docs.google.com/a/elementaryos.org/document/d/1Kc7BZlR2AZl6EeFTj8-qL2UOO4mg4JHpb-ymM2z3Vi4/edit?usp=sharing

**Comment by lewisgoddard** [comment]
Official screenshots for each?

**Comment by emersion** [comment]
Related to #405.

**Comment by cassidyjames** [comment]
Okay, dropping some recommended action items in here.

- [ ] Create a `/features` page with
- [ ] A list of features (see doc above)

Even with the app carousel, I don't think the site has a good spot for showing what our OS is, what features it includes, etc. For example, the guys on the [most recent episode of Bad Voltage](http://audio.lugradio.org/badvoltage/Bad%20Voltage%201x40.ogg) (at about 9:40) said,

> **Jeremy:** If you go to elementary.io, it says nothing about why it's better at all. An I think that's doing themselves a disservice.

> **Bryan:** It's a good looking website, but you're right, it is a little sparse on details.

Jeremy then mentions things we should be showing off like the new notifications, Contractor, and smart paste in the Terminal. 

Essentially people don't know that we've done _more_ than "just" a theme and some apps, and we should tell people about that. :)

**Comment by danrabbit** [comment]
Re-titling this report. I'm not convinced that the home page isn't the features page. Why should someone navigate to a new separate page?

**Comment by xweque** [comment]
Besides a feature page wouldn't it be a good idea to create a online tour, like the one Ubuntu have (but better, prettier and with animations and stuff) (http://www.ubuntu.com/tour/en/)? Then the user wouldn't just see that we provide good features but that the environment is fluid and productive.

One could argue that it would be hard to make it browser compatible (ie), but is the Elementary OS target demographic normally IE users?

**Comment by emersion** [comment]
@xweque A good start would be http://webos.symbiose.fr.cr/ (a modified version of Symbiose to create an online elementary tour is available here: https://github.com/symbiose/elementary-demo, screenshots here: https://plus.google.com/u/0/115825269531819402710/posts/1q6aXmsLQAg)

But @danrabbit already said this isn't a good idea since users could decide not to install elementary because there are bugs on the online version. We can't reproduce exactly elementary's ui accross all browsers.

**Comment by xweque** [comment]
We may not be able to do it in all browsers, but say doing it for Firefox, Chrome, Safari and Opera wouldn't be that hard and that would account for about 85% (rough value, estimated, not elementary's starts) of all traffic from desktop. They are all very similar in behaviour. We could simply detect the users browser and disable them from visiting/not show the link to the tour if they are using the wrong browser.

Saying a bug might chase people away might be true, but I think many people don't try Elementary since they don't know what it's about; why not keep Windows/OSX/current Linux? You gotta ask yourself what Ubuntu had in mind putting their laggy and ugly tour up if they didn't expect more downloads/user interest :)

Also as a final note I think Symbios might be a bit too much (couldn't get the elementary version to work though, only the online version). It would be difficult to maintain and in such a "huge" application with more complex features bugs would be much more lightly. A better way would be to make something simple, just having the default applications and features of Pantheon/Elementary. You may not be able to show off notifications without forcing them upon the user, but showing off the new (epic) Multitasking View would come naturally.

**Comment by danrabbit** [comment]
I'm very -1 to an imitation. This is a hard "no". We can advertise the OS features in an engaging manner without doing this.

**Comment by cassidyjames** [comment]
After discussion with @danrabbit, we decided that the home page _is_ the features page and that we don't need a separate page.
