### ISSUE TITLE
Blog should share same navigation as main site [$30]

### ISSUE THREAD

**Issue by quassy** [elementary/mvp#609]
Even though the blog is hosted on Tumblr this should not stop it from being visually integrated into the main site as Tumblr supports [custom theming](https://www.tumblr.com/docs/de/blog_customization). Starting off I'd suggest implementing the main nav from mvp for the Tumblr page, later maybe also the footer.

**Comment by cassidyjames** [comment]
@danrabbit I copied the DOM and CSS from the nav to http://blog.elementary.io/. Thoughts?

**Comment by danrabbit** [comment]
Looks good to me. Marking as closed :)

**Comment by quassy** [comment]
Is it possible to localize the navbar on tumblr? Not that it makes a lot of sense considering the blog is solely in English...

**Comment by lewisgoddard** [comment]
@quassy I don't think so, not with the existing options from there.

**Comment by cassidyjames** [comment]
@quassy @lewisgoddard the only way I can think of there is to iframe-embed the blog, similar to how we do the store. However, Tumblr isn't designed to be embedded whereas Square is. I don't think it's worth pursuing because then we have two URLs for the blog (blog.elementary.io and elementary.io/blog, for example) and it gets messy. :)

**Comment by quassy** [comment]
I agree. 

Btw I think /blog should 301-redirect to blog.

**Comment by lewisgoddard** [comment]
+1 to redirecting `/blog`

**Comment by cassidyjames** [comment]
Open a new issue ;)
