### ISSUE TITLE
Create a permalink for latest beta

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#61]
So we don't have to modify this page every time we make a new ISO, we should set up a permalink

**Comment by lewisgoddard** [comment]
When this site becomes elementary.io, do we want betas to still be available on the sub-domain, or do we want an elementary.io/beta page?

**Comment by KeitIG** [comment]
or why not a elementary.io/next ? Beta wil not be a beta forever.

**Comment by lewisgoddard** [comment]
I suppose it could also be an alpha or rc, so /next makes more sense. We might want to use the blueprint background on that page :)

**Comment by fabianthoma** [comment]
So I'd like to revive the discussion on this, especially since we are now moving closer to doing a new release and the whole beta/rc testing that goes along with it. I'd love to provide curious people a site where they can get the latest (and accurate) info on our development process and upcoming releases.
Downloading them from there is ofc a must. So maybe we should tackle this now and put up a page talking a bit about loki and that we are working on it. Then when we have a beta also put it up there.

**Comment by danrabbit** [comment]
This might be unpopular opinion penguin, but I think we should make dailies part of the developer account package. So that would mean linking from the Houston/developer dashboard (after login). It would add more value to the account and hopefully attract more people to sign up. Google+ polling indicated people would be willing to pay $10-$20/yr, and comments indicated they'd be willing to pay $50-$100/yr.

My guess is that it wouldn't take long for these dailies/betas/rcs to show up on (for example) pirate bay, which would add to the excitement/feeling of exclusivity. Create more buzz, etc.

**Comment by lewisgoddard** [comment]
The last time this was brought up in Slack, the design decision was to not have a beta page and link to it from `/developer` (although that may be because `/developer` isn't getting as much love as `/get-involved`, there is a lot of overlap).
