### ISSUE TITLE
/get-involved is ordered strangely.

### ISSUE THREAD

**Issue by lewisgoddard** [elementary/mvp#679]
I think we get bug reports filed on web for desktop stuff because web comes first. Considering how desktop and design orientated elementary is, this seems strange. I actually think the order could do with being nearly reversed.

Current order:
1. Translations
2. Web Development
3. Design
4. Desktop Development
5. Funding

Proposed order:
1. Design
2. Desktop Development
3. Funding
4. Web Development
5. Translations

**Comment by aleksandar-todorovic** [comment]
I would put Translations between Desktop Development and Web Development. Since it is related to both of them, it makes kind of natural transition in my opinion. And I would put the funding on the top.

So, my suggestion is:

1. Funding
2. Design
3. Desktop Development
4. Translations
5. Web Development

**Comment by souravsingh** [comment]
I would like to work on this issue.How do I work on it?

**Comment by lewisgoddard** [comment]
You'll need to get an approved re-order from the UX team, probably @danrabbit @snwh or @cassidyjames. Then you'll probably just need to move the sections and links to them.

**Comment by harveycabaguio** [comment]
I ordered them like that in my design of the get involved because I wanted to order them from easiest to hardest to contribute to. To me, translations would be simple, then web because html/css is easy to pick up, etc.

**Comment by danrabbit** [comment]
I agree with Harvey. If we wanted to move funding to the top, the easiest thing to do would be to just shuffle down the light colored sections. So it would be:

Funding
Web Development
Translations
Desktop Development
Design

I don't think I'd put design or desktop at the top because they're much harder to get into.

**Comment by lewisgoddard** [comment]
Alternating light and dark isn't an issue I don't think, I filed this because I thought the web "report bug" link was higher up, and therefore more prominent, than the design and desktop side of things.

**Comment by souravsingh** [comment]
So the order given by @danrabbit is the one to go for, am I right?

**Comment by lewisgoddard** [comment]
As it stands, probably, but I'm not sure I agree. I definitely think design should not be last, it's probably our most prominent focus.

**Comment by spitzl** [comment]
1. Design
2. Desktop Development
3. Translations
4. Web Development
5. Funding
This way Design is first and Funding is last. AIDA: attention, interest, desire, action.
Give it a thought.
