### ISSUE TITLE
If I visit a non-English link, don't take it as my language of choice

### ISSUE THREAD

**Issue by aleksandar-todorovic** [elementary/mvp#771]
Sorry if the title is not very descriptive, I can't seem to find a title that sums it up.

Currently, if I visit the link to a site in some foreign language (like `/ro` which I visited recently), the site automatically assumes that this is the language I'm going to continue using. When I visited the site again, it automatically redirected me to `/ro/...` page.

I don't think that this is an expected behavior.

**Comment by lewisgoddard** [comment]
The site does currently assume that if you visit a language page that that is the language you want in the future. We can't change that behaviour because then people who do want that language will have to change it for every page they visit.

Instead, the expected behaviour from the user is to change the language if they click a link in a different language, as I assume you had to later.

**Comment by aleksandar-todorovic** [comment]
Then this is a feature, not a bug. :)
