### ISSUE TITLE
There are some translation mistakes on your main page (German)

### ISSUE THREAD

**Issue by N1cl4s** [elementary/mvp#844]
For example: 
Freya herunterladen (free download) = Kostenlos herunterladen (that would be the correct translation)
I tried to find the translation part on transifex.com but couldnt find it.

**Comment by lewisgoddard** [comment]
I think you've misunderstood the phrase slightly, Freya Download is the original string, Freya being the version name, and as such it's never translated. Since you seem to think "herunterladen" is correct, I'm going to mark this as closed, although there does seem to be a larger problem with organisation.
