### ISSUE TITLE
Document Glib.Notification [$50]

### ISSUE THREAD

**Issue by danrabbit** [elementary/mvp#935]
Should add docs about how to use notifications with Glib.Notification.

https://www.bountysource.com/issues/28858552-document-glib-notification

**Comment by desiderantes** [comment]
I want to tackle on this, but it's more than what the title may suggest: In order to get GLib.Notifications to show up properly, you need an GLib.Application subclass, a .desktop file, and if you want to offer buttons, GLib Actions and D-BUS activation. I think that's a load of prerequisites that the guide would only touch lightly (but you'll need to understand), so maybe change the description, or create separate bugs for them.

**Comment by danrabbit** [comment]
Hey @desiderantes, You're right, it would cover creating a GLib.Application subclass. Our guide already covers [creating a .desktop file](https://elementary.io/docs/code/getting-started#the-desktop-file) so you would only need to mention amending it. As of this moment, buttons aren't supported by Gala's notification server, so it wouldn't need to cover explicit buttons.

**Comment by danrabbit** [comment]
I think @Philip-Scott may have already started working on this. Pinged him this morning to make sure he assigns himself if he is

**Comment by desiderantes** [comment]
Ok, i'll drop what i currently have

 
 
  El sáb., dic. 5, PM a 12:55 PM, Daniel Foré<notifications@github.com> escribió:   
I think @Philip-Scott may have already started working on this. Pinged him this morning to make sure he assigns himself if he is
