### ISSUE TITLE
Remove The Big Lebowski reference in the HIG

### ISSUE THREAD

**Issue by linusbobcat** [elementary/mvp#955]
Look I get it. I've watched the movie and find the (full) quote hilarious. It's great at getting the point across in *English*. However, I really think this should be removed for the following reasons:

- Translations; it's not that practical to really translate or link to IMDB with this string.
- It uses cultural specific references that only make sense to North Americans or Europeans which violates the HIG.
- The complete quote is a bit NSFW. I'm not a fan of the SJW crowd, but the full quote does violate the community code of conduct.

**Comment by snwh** [comment]
Yeah, well, you know, that's just, like, your opinion, man.

**Comment by snwh** [comment]
(I couldn't resist) 

However, I'm inclined to agree with you. We can probably find a better way to say that design isn't just the opinion of designers.

**Comment by embik** [comment]
I oppose this because I consider it ridiculous.

* Linux (and UNIX before) is full of western pop culture references. If we want to follow this consequently, we will have to patch _alot_ applications for no good reason. As developers we're in general heavily influenced by this.
* elementary OS _is_ primarily developed by people influenced by western pop culture. I don't believe there is a single contributor on Slack who doesn't know the movie (or at least heard the name and/or the quote in question).
* While people unfamiliar with the reference might be a bit puzzled, I'm pretty sure they're intelligent enough to search for it if they feel the need to understand it. We're on the Internet after all.
* The quote in question is not only part of western pop culture but also part of "Internet" culture - It's been posted and referenced innumerable times online. Nearly everyone participating in English-speaking communities has encountered it at least once. The assumption developers do not speak English at all is absurd (and aren't able to participate in those communities), nearly all resources for developers are written in English.
* Assuming this is offending or unsettling is highly speculative. As long as there is nobody from another cultural sphere actually complaining I don't see why we should change it. It doesn't bother anyone most likely anyway.
* Violence and swearing is part of our reality, whether you like that or not. The Internet is not a "safe space". The full quote is not on the page anyway so I'm not sure why the classification of the "full quote" has relevance.

**Comment by linusbobcat** [comment]
I've elaborated my thoughts below:

- My most important concern is that It's tricky to translate. This is both a technical issue, because it consists of a link with words in it that are heavily tied to English, and because it uses some slang. The translated string would also be less effective than the English one depending on the culture and language conventions. If some translators could comment on this however, that would be great.

- Yes cultural references are great, but this sentence, despite being in a humorous tone, is meant to communicate an important message, that "design isn't just an opinion". Including Easter eggs is one thing, but relying on pop culture to communicate a message is another thing. It sounds great in English, and I find it hilarious, but what about in other languages? The fact that someone would have to Google it up makes the sentence less effective. The HIG should be as clear as possible in multiple languages, and shouldn't rely on pop culture to say something important; in fact, that's what the HIG says.

- The complete linked quote isn't that relevant to the idea it's trying to communicate. If it linked to an informative article, fine, except that it links to a quote where it's just a couple of guys cursing. This something I personally have **no** problem with, it's just that it's out of context. The quote doesn't expand on the Dude's idea that "Yeah, well, you know, that's just, like, your opinion, man," instead it just shows the pieces of dialog that come before and after that quote which makes no sense to people who haven't watched the movie or that clip.

- My last point, which is my most insignificant important point, has nothing to do about "safe spaces", SJWs or that nonsense which I personally despise. Yes violence and swearing is real, but my point is that it's also being slightly hypocritical for elementary to link to that with their current Code of Conduct. Also I consider it to be slightly NSFW, as in Not Safe For *Work*, in some corporate environments. I personally have no problem with the quote.

**Comment by embik** [comment]
I actually just realized that for example the German translation does not contain the reference (nor the link) and just says "design is not just a matter of taste" (_Design ist nicht nur Geschmackssache_). It looks like the translators already took into account not to translate language-specific references.

**Comment by linusbobcat** [comment]
If the translators have no issue with it, that part is settled then.

My reason for creating this issue isn't about political correctness, but rather as a  question how effective it is at communicating. Since it looks like that is a non-issue, cool. 

However, I still stance on my last two concerns, that linking to the quote is out of context and that it's less accessible in some corporate environments.

**Comment by KeitIG** [comment]
After a quick read, (begging your pardonif I forget something), if we want to keep this quote, this is something we should comment in Transifex (e.g "care, quote from The Big Lebowski'')

**Comment by danrabbit** [comment]
I do think having pop culture references makes the docs more fun. Docs are boring. If we can make them fun somehow, I'd like to do that. That said, I understand the concerns. I'd recommend that we:

- [ ] Remove the IMDB link. Either you get the reference or you don't. Linking the quote doesn't make it any clearer and brings in those language concerns. I don't think we need to link it.

- [ ] Make a note for translators that they shouldn't try to translate this word for word and it's okay (maybe even recommended) not to translate the quote. As Martin pointed out, I think good translations should be more about carrying the message across and not try to hard to be exact literal translations. If this doesn't make sense in languages other than English, it shouldn't be translated.

**Comment by linusbobcat** [comment]
I agree with @danrabbit's suggestions.
